## Future Sales

In [1]:
##libraries
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from sklearn import preprocessing

In [2]:
file_train = "data/sales_train.csv"
file_test = "data/test.csv"

In [3]:
df = pd.read_csv(file_train)
df

date  date_block_num  shop_id  item_id  item_price  \
0        02.01.2013               0       59    22154      999.00   
1        03.01.2013               0       25     2552      899.00   
2        05.01.2013               0       25     2552      899.00   
3        06.01.2013               0       25     2554     1709.05   
4        15.01.2013               0       25     2555     1099.00   
...             ...             ...      ...      ...         ...   
2935844  10.10.2015              33       25     7409      299.00   
2935845  09.10.2015              33       25     7460      299.00   
2935846  14.10.2015              33       25     7459      349.00   
2935847  22.10.2015              33       25     7440      299.00   
2935848  03.10.2015              33       25     7460      299.00   

         item_cnt_day  
0                 1.0  
1                 1.0  
2                -1.0  
3                 1.0  
4                 1.0  
...               ...  
2935844           1.0  
2935845           1.0  
2935846           1.0  
2935847           1.0  
2935848           1.0  

[2935849 rows x 6 columns]

In [4]:
# Features (columns) will be used
# X_columns = ['date_block_num', 'shop_id', 'item_id']
X_columns = ['date_block_num', 'shop_id']

In [5]:
df2 = df.groupby(X_columns).sum().reset_index()
df2 = df2.drop(['item_id', 'item_price'], axis=1)
df2

date_block_num  shop_id  item_cnt_day
0                  0        0        5578.0
1                  0        1        2947.0
2                  0        2        1146.0
3                  0        3         767.0
4                  0        4        2114.0
...              ...      ...           ...
1581              33       55        1972.0
1582              33       56        1263.0
1583              33       57        2316.0
1584              33       58        1446.0
1585              33       59         790.0

[1586 rows x 3 columns]

In [6]:
# Convert to Array
X = df2[X_columns].values
y = df2['item_cnt_day'].values

In [7]:
# Scale the data
scaler = preprocessing.StandardScaler()
scaler.fit(X)
X = scaler.transform(X.astype(float))
X 

array([[-1.70880101, -1.80470541],
       [-1.70880101, -1.74705081],
       [-1.70880101, -1.6893962 ],
       ...,
       [ 1.71377092,  1.48160698],
       [ 1.71377092,  1.53926158],
       [ 1.71377092,  1.59691618]])

In [8]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (1268, 2) (1268,)
Test set: (318, 2) (318,)


In [9]:
X_train

array([[-1.3976581 ,  1.48160698],
       [ 0.78034221, -0.36334033],
       [ 0.26177071, -1.6893962 ],
       ...,
       [ 0.36548501,  0.67444253],
       [ 0.36548501, -0.36334033],
       [ 0.98777082,  1.25098856]])

In [10]:
y_train

array([5493., 6611.,  956., ..., 1873., 6158., 1378.])

In [11]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
preds = lr.predict(X_test)
lrmse = mean_squared_error(y_test,preds)
print("Mean Sqaured Error for Logistic Regression is {}".format(lrmse))

Mean Sqaured Error for Logistic Regression is 3504654.682389937


In [ ]:
from sklearn import svm
svr = svm.SVR()
svr.fit(X_train, y_train)

In [ ]:
# start 10:43am

In [ ]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train,Y_train)
preds = gbc.predict(X_test)
gbc_accuracy = accuracy_score(Y_test, preds)
print(f'GradientBoostClassifier accuracy: {gbc_accuracy*100}')

In [ ]:
svc = SVC()
svc.fit(X_train,y_train)
preds = svc.predict(X_test)
svc_accuracy = accuracy_score(y_test, preds)
print(f'SVC accuracy: {svc_accuracy*100}')

In [ ]:
X_train

In [ ]:
y_train

In [ ]:
X_test

In [ ]:
y_test

In [ ]:
preds