### Best fit circle in 2D space

Define a circle
- Center point
- Radius

In 2D space
- A line can be determined by 2 points
- A circle can be determined by 3 points

In [18]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv("data_2d_circle.csv", header=None)
df.head()

0           1
0   99.951002  201.015590
1  100.070156  199.016258
2  100.921381  200.068597
3   99.031849  199.895546
4   99.469357  200.869111

In [16]:
pts = df.to_numpy()
pts[0:5]

array([[ 99.9510022, 201.01559  ],
       [100.0701559, 199.016258 ],
       [100.921381 , 200.0685969],
       [ 99.031849 , 199.895546 ],
       [ 99.469357 , 200.869111 ]])

In [19]:
x = np.array([pts[:,0]]).T
y = np.array([pts[:,1]]).T

In [22]:
x_floor = np.floor(np.min(x, axis=0))
x_floor

array([99.])

In [20]:
x_min = np.min(x, axis=0)
x_max = np.max(x, axis=0)
y_min = np.min(y, axis=0)
y_max = np.max(y, axis=0)
print(x_min, x_max, y_min, y_max)

[99.031849] [100.921381] [199.016258] [201.01559]


In [21]:
import plotly.graph_objects as go

fig = go.Figure()

# points
scatter = go.Scatter(
    x=pts[:,0],
    y=pts[:,1],
    mode="markers",
    marker={
        'size':4,
        'color':'red'},
    name="points"
)
fig.add_trace(scatter)

fig.show()

In [ ]:
# Set axes properties
fig.update_xaxes(range=[0, 4.5], zeroline=False)
fig.update_yaxes(range=[0, 4.5])

# Add circles
fig.add_shape(type="circle",
    xref="x", yref="y",
    x0=1, y0=1, x1=3, y1=3,
    line_color="LightSeaGreen",
)

# Set figure size
fig.update_layout(width=600, height=600)

In [108]:
# 
points = np.array([[1,6],
                  [3,2],
                  [8,5]])

In [109]:
points

array([[1, 6],
       [3, 2],
       [8, 5]])

In [110]:
x1,y1 = points[0]
x2,y2 = points[1]
x3,y3 = points[2]

In [87]:
m = (y1 - y2)/(x1 - x2)
b = y1 - m * x1
m, b

(-2.0, 8.0)

In [88]:
y1n = b + m * x1
y1, y1n

(6, 6.0)

In [91]:
line_x1 = 1
line_y1 = b + line_x1 * m
line_x2 = 3
line_y2 = b + line_x2 * m
line_x1, line_y1, line_x2, line_y2

(1, 6.0, 3, 2.0)

In [98]:
x12,y12 = x1+(x2-x1)/2, y1+(y2-y1)/2
x1n = x1 + (x2 - x1) * 2
y1n = y1
m12 = (y1n - y2) / (x1n - x2)
b12 = y12 - m12 * x12
m12, b12

(2.0, 0.0)

In [105]:
x12,y12 = x1+(x2-x1)/2, y1+(y2-y1)/2
m12 = -1/m
b12 = y12 - m12 * x12
m12, b12

(0.5, 3.0)

In [106]:
line2_x1 = 1
line2_y1 = b12 + line2_x1 * m12
line2_x2 = 3
line2_y2 = b12 + line2_x2 * m12
line2_x1, line2_y1, line2_x2, line2_y2

(1, 3.5, 3, 4.5)

In [111]:
m2 = (y2-y3)/(x2-x3)
b2 = y2 - x2*m2
m2,b2

(0.6, 0.20000000000000018)

In [112]:
line23_x1 = 3
line23_y1 = b2 + m2 * line23_x1
line23_x2 = 8
line23_y2 = b2 + m2 * line23_x2
line23_x1, line23_y1, line23_x2, line23_y2

(3, 2.0, 8, 5.0)

In [114]:
x23, y23 = x2 + (x3-x2)/2, y2+(y3-y2)/2
x23, y23

(5.5, 3.5)

In [116]:
m23 = -1/m2
b23 = y23 - m23 * x23
m23, b23

(-1.6666666666666667, 12.666666666666668)

In [117]:
line23_norm_x1 = 3
line23_norm_y1 = b23 + m23 * line23_norm_x1
line23_norm_x2 = 8
line23_norm_y2 = b23 + m23 * line23_norm_x2
line23_norm_x1, line23_norm_y1, line23_norm_x2, line23_norm_y2

(3, 7.666666666666668, 8, -0.6666666666666661)

In [122]:
center_x = -1 * (b12 - b23)/(m12 - m23)
center_y = b12 + m12 * center_x
center_x, center_y

(4.461538461538462, 5.230769230769231)

In [124]:
r = np.sqrt((center_x - x1)**2 + (center_y - y1)**2)
r

3.5459786374203413

In [125]:
x_min = center_x - r
x_max = center_x + r
y_min = center_y - r
y_max = center_y + r

In [127]:
fig = go.Figure()

# points
scatter1 = go.Scatter(
    x=points[:,0],
    y=points[:,1],
    mode="markers",
    marker={
        'size':4,
        'color':'red'},
    name="points"
)

scatter2 = go.Scatter(
    x=[x12, x23, center_x],
    y=[y12, y23, center_y],
    mode="markers",
    marker={
        'size':4,
        'color':'green'},
    name="points"
)

fig.add_shape(type="line",
    x0=line_x1, y0=line_y1, x1=line_x2, y1=line_y2,
    line=dict(color="RoyalBlue",width=1)
)

fig.add_shape(type="line",
    x0=line2_x1, y0=line2_y1, x1=line2_x2, y1=line2_y2,
    line=dict(color="RoyalBlue",width=1)
)

fig.add_shape(type="line",
    x0=line23_x1, y0=line23_y1, x1=line23_x2, y1=line23_y2,
    line=dict(color="RoyalBlue",width=1)
)

fig.add_shape(type="line",
    x0=line23_norm_x1, y0=line23_norm_y1, x1=line23_norm_x2, y1=line23_norm_y2,
    line=dict(color="RoyalBlue",width=1)
)

fig.add_shape(type="circle",
    x0=x_min, y0=y_min, x1=x_max, y1=y_max,
    line_color="LightSeaGreen",
)

fig.add_trace(scatter1)
fig.add_trace(scatter2)

fig.update_xaxes(range=[0, 10])
fig.update_yaxes(range=[0, 10])

fig.update_layout(width=600, height=600)

fig.show()

In [34]:
x12,y12

(-0.05957699999999733, -99.000334)